gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
models/zm_rockhouse2/clothing_pile_01.mdl
models/zm_rockhouse2/eeekrovat.mdl
models/zm_rockhouse2/eeeshkaf.mdl
models/zm_rockhouse2/fen2.mdl
models/zm_rockhouse2/flo_grass.mdl
models/zm_rockhouse2/lamppost.mdl
models/zm_rockhouse2/leafy.mdl
models/zm_rockhouse2/pi_tree3.mdl
models/zm_rockhouse2/pi_twig.mdl
models/zm_rockhouse2/wood.mdl
models/zm_rockhouse2/zm_couch.mdl
sound/zm_rockhouse2/3dmeagle.wav
sound/zm_rockhouse2/crow.wav
sound/zm_rockhouse2/phone.wav
sound/zm_rockhouse2/rats4.wav
sound/zm_rockhouse2/wind.wav
sound/zm_rockhouse2/wind_tunnel1.wav
sound/zm_rockhouse2/windmill_wind.wav
sound/zm_rockhouse2/zp_fire.wav
sprites/zm_rockhouse2/flame01.spr
sprites/glow01.spr

